#!/bin/bash                                                                                                                                                                                                                      
                                                                                
files=(*$1*)                                                                    
                                                                                
i=0                                                                             
for filename in ${files[*]}; do                                                 
    echo $i: $filename                                                          
    i=`expr $i + 1`                                                             
done                                                                            
                                                                                
read input_var                                                                  
                                                                                
read -a arr <<<$input_var                                                       
                                                                                
echo vim ${files[${arr[0]}]}                                                    
vim ${files[${arr[0]}]}
